### ISSUE TITLE
There is no clean way to keep build dependencies out of the marginalia docs

### ISSUE THREAD

**Issue by nogden** [francesco-bracchi/boot-marginalia#2]
Documentation generated by marginalia lists the dependencies at the top of the page. These dependencies are taken from the `:dependencies` key in the boot environment. Since boot has no concept of Leiningen's `:dev-dependencies`, all of the dependencies, including build dependencies must go in the environments `:dependencies` list. This means that build dependencies, including marginalia itself, are listed in the generated documentation.

Currently, I have resorted to setting up boot-marginalia in my profile.boot. This solves the issue, but it means that anyone who decides the build the project from source is unable to build the documentation unless they first, manually set up boot-marginalia, which is less than ideal. It also means that tasks in build.boot cannot compose the marginalia task as there is no guarantee that it is available due to its absence from the `:dependencies` list.

We need another way of allowing boot-marginalia to be present in the dependencies array, but not present in the documentation output. Ideally, there would be a way to selectively include or exclude any dependency from the list that is rendered in the documentation.

**Comment by francesco-bracchi** [comment]
boot doesn't have the concept of `:dev-dependencies` but for that purpose the [:scope](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope) keyword is used instead, I'm thinking to an explicit _deps_ parameter for the task that gives the developer the control over the dependencies list, and the default value should be the dependencies for which the scope is not `"test"` or `"provided"`

**Comment by nogden** [comment]
That sounds sensible to me. Would you like me to put a patch together or are you happy to do this?

**Comment by francesco-bracchi** [comment]
I'll do by myself, thank you.

**Comment by francesco-bracchi** [comment]
fixed by v0.1.3
